### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by tudorbarascu** [qwat/QWAT#2]
Hi and thank you for your really nice work,
I am trying to get the qWat plugin working without success.
Steps:
clone https://github.com/3nids/qWat
cd qWat
git submodule init
git update
make all
make deploy
Couldn't load plugin qwat due an error when calling its classFactory() method

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 204, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/home/web/.qgis2/python/plugins/qwat/**init**.py", line 4, in classFactory
    from qwat import qWat
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 453, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/web/.qgis2/python/plugins/qwat/qwat.py", line 33, in 
    from gui.mysettingsdialog import MySettingsDialog
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 453, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ImportError: No module named mysettingsdialog

Should I have taken other steps?

**Comment by leshobster** [comment]
Hi, I've been trying to make this plugin work, but I've stumbled into the same error - ImportError: No module named mysettingsdialog. Are there any updates on this issue?

**Comment by tudorbarascu** [comment]
Hi,
The plugin is obsolete.
You just need the database model and the qgs project.
See https://github.com/qwat/qWat/pull/20 for more details.
