### ISSUE TITLE
deploy release fails to upload dump to release files

### ISSUE THREAD

**Issue by haubourg** [qwat/QWAT#241]
Hi Matthias, 
I tagged 1.3.0 in QWAT to test the deploy logic for automatically creating release and push dumps to release file. 
Release is created smoothly, but upload fail without much logs:
https://travis-ci.org/qwat/qwat-data-model/builds/309517936#L5868

Any idea?

**Comment by haubourg** [comment]
@m-kuhn ping

**Comment by haubourg** [comment]
````
Traceback (most recent call last): File "./.deploy/create_release.py", line 170, in <module> main() File "./.deploy/create_release.py", line 128, in main 'Authorization': 'token {}'.format(os.environ['GH_TOKEN']) File "/home/travis/virtualenv/python3.5.3/lib/python3.5/os.py", line 725, in __getitem__ raise KeyError(key) from None KeyError: 'GH_TOKEN'
````

**Comment by haubourg** [comment]
Solved ! thanks a lot!
